version: "3.7"
services:
  boarding-manager-api:
    image: boarding-manager:latest
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          memory: 2048M
