#api
spring:
  profiles:
    active: prod
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
    majorVersion: '@parsedVersion.majorVersion@'
  hateoas:
    use-hal-as-default-json-media-type: false   
  #datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo-db
    username: sa

  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect     
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: true

  #h2
  h2:
    console:
      enabled: true 
      path: /h2-console
      settings:
        web-allow-others: true

#Documentação
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    tagsSorter: alpha
  cache:
    disabled: true